version: '3.8'

networks:
  eldoradoNetwork:
    name: eldoradoNetwork
    driver: bridge

volumes:
  mongo:

services:

  mongo:
    image: mongo:latest
    container_name: "mongo-eldorado"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null


  application:
    build: ../
    container_name: application-segunda-semana
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/imc-calculator?retryWrites=true&w=majority&ssl=false
